### ISSUE TITLE
Question about the way to compute image difference.

### ISSUE THREAD

**Issue by KittyStore** [MCG-NJU/MGSampler#1]
Thank you for your great work. 
My question is that why you use the function skimage.measure.compare_ssim to compute the similarity of two adjacent frames instead of subtracting directly as your paper says.

**Comment by castle971005** [comment]
Thanks for the question.
The function compare_ssim can calculate the average structural similarity between the two images. It returns a score and a difference image. The score indicates the structural similarity index between the two input images, which falls in the range [-1,1], with values closer to 1 indicating higher similarity.
In practice, using the function compare_ssim and subtracting two adjacent frames directly actually give similar results.

**Comment by KittyStore** [comment]
收到！感谢您的回复！😬

**Comment by zzzhhh1031** [comment]
> 收到！感谢您的回复！😬

Hello, please ask if you are still here, can you add friends to communicate?
