### ISSUE TITLE
* motion represention is generated/saved in .json file.

### ISSUE THREAD

**Issue by mengjiac** [MCG-NJU/MGSampler#2]
I have same questions,After i took a earnest look at your code .how is the JSON file generated.i would appreciate your reply.

**Comment by yztongzhan** [comment]
Hi @mengjiac! Please use [generate_img_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_img_diff.py) or [generate_feature_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_feature_diff.py) to generate the JSON file of motion represention.

**Comment by mengjiac** [comment]
> Hi @mengjiac! Please use [generate_img_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_img_diff.py) or [generate_feature_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_feature_diff.py) to generate the JSON file of motion represention.

state_dict = torch.load('/home/zhiyuan/PAN/PAN_PA_something_resnet50_shift8_blockres_avg_segment8_e80.pth.tar')
I don't have the file.can you give me this file? I would be very greatful.thinks a lot.

**Comment by yztongzhan** [comment]
We have mentioned the checkpoint [here](https://github.com/MCG-NJU/MGSampler#acknowledgement).

**Comment by zzzhhh1031** [comment]
> 嗨@mengjiac！请使用[generate_img_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_img_diff.py)或[generate_feature_diff.py](https://github.com/MCG-NJU/MGSampler/blob/main/generate_feature_diff.py)生成运动表示的 JSON 文件。

Hello, I am also having trouble generating json files. I don't know how to change the path in the code, can I communicate with you, look forward to a reply

**Comment by zzzhhh1031** [comment]
> 我有同样的问题，在我认真看了你的代码.如何生成JSON文件之后，我将不胜感激你的回复。

您好，我也在关注这篇文章，也在复现，可以加个好友交流吗 期待回复

**Comment by zyx-cv** [comment]
> 

你好 请问你复现完了吗 想问问generate_featrue_diff得到的一维向量归一化后选帧的时候又要归一化一次吗

**Comment by zyx-cv** [comment]
> > 我有同样的问题，在我认真看了你的代码.如何生成JSON文件之后，我将不胜感激你的回复。
> 
> 您好，我也在关注这篇文章，也在复现，可以加个好友交流吗 期待回复

你好 请问你复现完了吗 想问问generate_featrue_diff得到的一维向量归一化后选帧的时候又要归一化一次吗

**Comment by zyx-cv** [comment]
> > 我有同样的问题，在我认真看了你的代码.如何生成JSON文件之后，我将不胜感激你的回复。
> 
> 您好，我也在关注这篇文章，也在复现，可以加个好友交流吗 期待回复

您好，我现在也在关注这篇文章，可以加个好友交流下吗
