### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by zzzhhh1031** [MCG-NJU/MGSampler#3]
Hello, I reported these two problems after running the script file, what is the reason？

KeyError: 'SampleFrames is already registered in pipeline'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1525602) of binary: /home/zhouyx/anaconda3/envs/open-mmlab/bin/python

**Comment by isno0907** [comment]
I had the same problem and I solved it.
`KeyError: 'SampleFrames is already registered in pipeline'`

You have to delete line 82 of mmaction/datasets/pipelines/loading.py which is repeated twice.

**Comment by zzzhhh1031** [comment]
> 我有同样的问题，我解决了它。 `KeyError: 'SampleFrames is already registered in pipeline'`
> 
> 您必须删除 mmaction/datasets/pipelines/load 的第 82 行.py该行重复两次。

Yes, I fixed this problem before. Please ask you are also reproducing this work, you can add friends to communicate
