### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by zyx-cv** [MCG-NJU/MGSampler#4]
Is there a trained model could be provided. I just want to do a test. Thanks.

**Comment by kanonjz** [comment]
Hi bro, have you obtained the trained model or trained successfully by yourself?

**Comment by zyx-cv** [comment]
I tried to train a model, but i did not reach the same accuracy. Have you done it.&nbsp;


I’m&nbsp;张玉想??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 晚上7:58
收件人: ***@***.***&gt;; 
抄送: "I’m ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [MCG-NJU/MGSampler] trained model (Issue #4)





 
Hi bro, have you obtained the trained model of trained successfully by yourself?

**Comment by zyx-cv** [comment]
> 

没有达到作者的精度 有些甚至低于baseline 在检查代码 请问你实现了吗

**Comment by zyx-cv** [comment]
> 没有达到作者的精度 有些甚至低于baseline 在检查代码 请问你实现了吗

没有达到作者的精度 有些甚至低于baseline 在检查代码 请问你实现了吗

**Comment by zyx-cv** [comment]
> Hi bro, have you obtained the trained model or trained successfully by yourself?

没有达到作者的精度 有些甚至低于baseline 在检查代码 请问你实现了吗
